### ISSUE TITLE
Stimulus: Add events to add custom JS

### ISSUE THREAD

**Issue by daFish** [stakovicz/ux-collection#1]
Like other UX-packages it would be great to have several events fired by the stimulus-controller, e.g. `this._dispatchEvent('collection:pre-connect', { options: payload.options });` like in https://github.com/symfony/ux/blob/main/src/Chartjs/Resources/assets/src/controller.js#L22

This would allow for further customization like modifying fields.

**Comment by stakovicz** [comment]
I added some events on the controller on this release :
https://github.com/stakovicz/ux-collection/tree/0.0.2
You can see the doc :
https://github.com/stakovicz/ux-collection#extend-the-default-behavior

**Comment by daFish** [comment]
Great I'll try it out and give you feedback.

**Comment by daFish** [comment]
@stakovicz After trying it out - which worked good - I think one event is missing from the controller: `_onAdd` 

Otherwise I was able to bind a custom library on a field from the collection.

**Comment by stakovicz** [comment]
@daFish You are right. I just added it.

You can choose the form theme and you have one for table.

**Comment by daFish** [comment]
@stakovicz The missing event is there. 🎉 

With the new update I haven't achieved the following:
* bind custom JS *after* a validation error occurred
* displaying the validation error message for the validated field
* customize the rendering of each form-field using form theming

**Comment by stakovicz** [comment]
> @stakovicz The missing event is there. 🎉
> 
> With the new update I haven't achieved the following:
> 
>     * bind custom JS _after_ a validation error occurred
I think this is not the responsability to this bundle
> 
>     * displaying the validation error message for the validated field
Your talking about the validation by Symfony with a constraint ?
> 
>     * customize the rendering of each form-field using form theming
How did you that ?
If you use the [classic method](https://symfony.com/doc/4.4/form/form_themes.html) with Symfony you should be able to override the default template of this bundle.

**Comment by daFish** [comment]
You can customize the rendering of each type by using generated blocks, e.g. `{% block *_entry_label %}{% endblock %}` - the asterisk is the value from `AbstractType::getBlockPrefix()`. You can do this for widget, row, label, help, and errors. With the help of these blocks you are able to theme them the way you want.
It would be nice to be able to have a bit more control over the various blocks your theme provides.

**Comment by stakovicz** [comment]
@daFish I don't see a problem with the theme overriding.
Here there is an example that works:
https://github.com/stakovicz/ux-collection-test/blob/main/templates/default/bootstrap_4.html.twig#L11-L27

Please note, I have just updated the bundle which includes a change of namespace.

**Comment by daFish** [comment]
@stakovicz I saw your code, saw my own mistake using form themes and now it is working as expected.

As my initial feature request was fulfilled, I'll close this issue. And I have to thank you for your incredible support.
